version: "3.8"

# Define services
services:
  # Nginx reverse proxy
  nginx:
    image: nginx:stable-alpine
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites:/etc/nginx/conf.d
    networks:
      - proxy_network

  # Web service
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    restart: always
    volumes:
      - app:/data
    ports:
      - 3000:3000
    networks:
      - proxy_network

  # Worker service
  worker:
    container_name: worker
    build:
      context: .
      dockerfile: ./apps/worker/Dockerfile
    restart: always
    volumes:
      - worker:/data
    ports:
      - 3001:3001
    networks:
      - proxy_network

  # Database service
  database:
    container_name: database
    command: -p 5432
    restart: always
    image: postgres:16
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - proxy_network

  # Redis service
  redis:
    container_name: redis
    restart: always
    image: redis:alpine3.16
    env_file:
      - .env
    ports:
      - 6379:6379
    command:
      redis-server --include /usr/local/etc/redis/redis.conf --appendonly yes
    volumes:
      - redis-data:/data
      - redis-conf:/usr/local/etc/redis/redis.conf
    networks:
      - proxy_network

# Define networks
networks:
  proxy_network:
    driver: bridge

# Define volumes
volumes:
  app:
  postgres:
  backups:
  worker:
  redis-data:
  redis-conf:
