-- AlterTable
ALTER TABLE "Asset" ALTER COLUMN "balance" SET DEFAULT '0',
ALTER COLUMN "balance" SET DATA TYPE TEXT,
ALTER COLUMN "costBasis" SET DEFAULT '0',
ALTER COLUMN "costBasis" SET DATA TYPE TEXT,
ALTER COLUMN "incomeRate" SET DATA TYPE TEXT,
ALTER COLUMN "interestBearingBalance" SET DATA TYPE TEXT,
ALTER COLUMN "realisedGain" SET DEFAULT '0',
ALTER COLUMN "realisedGain" SET DATA TYPE TEXT,
ALTER COLUMN "targetBalance" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "AssetTransaction" ALTER COLUMN "pricePerUnit" SET DATA TYPE TEXT,
ALTER COLUMN "quantity" SET DATA TYPE TEXT,
ALTER COLUMN "quantityFilled" SET DATA TYPE TEXT,
ALTER COLUMN "fee" SET DATA TYPE TEXT,
ALTER COLUMN "valueInBaseCurrency" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "Budget" ALTER COLUMN "totalBalance" SET DEFAULT '0',
ALTER COLUMN "totalBalance" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "BudgetEnvelope" ALTER COLUMN "remainingAmount" SET DEFAULT '0',
ALTER COLUMN "remainingAmount" SET DATA TYPE TEXT,
ALTER COLUMN "totalAmount" SET DEFAULT '0',
ALTER COLUMN "totalAmount" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "BudgetTransaction" ADD COLUMN     "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "deleted" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "deletedAt" TIMESTAMP(3),
ADD COLUMN     "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "pricePerUnit" SET DEFAULT '0',
ALTER COLUMN "pricePerUnit" SET DATA TYPE TEXT,
ALTER COLUMN "quantity" SET DEFAULT '0',
ALTER COLUMN "quantity" SET DATA TYPE TEXT,
ALTER COLUMN "quantityFilled" SET DATA TYPE TEXT,
ALTER COLUMN "fee" SET DEFAULT '0',
ALTER COLUMN "fee" SET DATA TYPE TEXT,
ALTER COLUMN "valueInBaseCurrency" SET DEFAULT '0',
ALTER COLUMN "valueInBaseCurrency" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "CashSnapshot" ALTER COLUMN "totalValue" SET DATA TYPE TEXT,
ALTER COLUMN "costBasis" SET DATA TYPE TEXT,
ALTER COLUMN "unrealisedGain" SET DATA TYPE TEXT,
ALTER COLUMN "realisedGain" SET DATA TYPE TEXT,
ALTER COLUMN "saleableValue" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "CryptoSnapshot" ALTER COLUMN "totalValue" SET DATA TYPE TEXT,
ALTER COLUMN "costBasis" SET DATA TYPE TEXT,
ALTER COLUMN "unrealisedGain" SET DATA TYPE TEXT,
ALTER COLUMN "realisedGain" SET DATA TYPE TEXT,
ALTER COLUMN "saleableValue" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "Cryptocurrency" ALTER COLUMN "balance" SET DEFAULT '0',
ALTER COLUMN "balance" SET DATA TYPE TEXT,
ALTER COLUMN "costBasis" SET DEFAULT '0',
ALTER COLUMN "costBasis" SET DATA TYPE TEXT,
ALTER COLUMN "realisedGain" SET DEFAULT '0',
ALTER COLUMN "realisedGain" SET DATA TYPE TEXT,
ALTER COLUMN "targetBalance" SET DEFAULT '0',
ALTER COLUMN "targetBalance" SET DATA TYPE TEXT,
ALTER COLUMN "interestBearingBalance" SET DEFAULT '0',
ALTER COLUMN "interestBearingBalance" SET DATA TYPE TEXT,
ALTER COLUMN "incomeRate" SET DEFAULT '0',
ALTER COLUMN "incomeRate" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "Market" ALTER COLUMN "name" DROP NOT NULL,
ALTER COLUMN "price" DROP NOT NULL,
ALTER COLUMN "price" DROP DEFAULT,
ALTER COLUMN "price" SET DATA TYPE TEXT,
ALTER COLUMN "priceChange24h" DROP NOT NULL,
ALTER COLUMN "priceChange24h" DROP DEFAULT,
ALTER COLUMN "priceChange24h" SET DATA TYPE TEXT,
ALTER COLUMN "priceChange24hPercent" DROP NOT NULL,
ALTER COLUMN "priceChange24hPercent" DROP DEFAULT,
ALTER COLUMN "priceChange24hPercent" SET DATA TYPE TEXT,
ALTER COLUMN "marketCap" DROP NOT NULL,
ALTER COLUMN "marketCap" DROP DEFAULT,
ALTER COLUMN "marketCap" SET DATA TYPE TEXT,
ALTER COLUMN "marketCapRank" DROP NOT NULL,
ALTER COLUMN "marketCapRank" DROP DEFAULT,
ALTER COLUMN "marketCapRank" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "PortfolioSnapshot" ALTER COLUMN "totalValue" SET DATA TYPE TEXT,
ALTER COLUMN "costBasis" SET DATA TYPE TEXT,
ALTER COLUMN "unrealisedGain" SET DATA TYPE TEXT,
ALTER COLUMN "realisedGain" SET DATA TYPE TEXT,
ALTER COLUMN "saleableValue" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "PropertySnapshot" ALTER COLUMN "totalValue" SET DATA TYPE TEXT,
ALTER COLUMN "costBasis" SET DATA TYPE TEXT,
ALTER COLUMN "unrealisedGain" SET DATA TYPE TEXT,
ALTER COLUMN "realisedGain" SET DATA TYPE TEXT,
ALTER COLUMN "saleableValue" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "SecuritySnapshot" ALTER COLUMN "totalValue" SET DATA TYPE TEXT,
ALTER COLUMN "costBasis" SET DATA TYPE TEXT,
ALTER COLUMN "unrealisedGain" SET DATA TYPE TEXT,
ALTER COLUMN "realisedGain" SET DATA TYPE TEXT,
ALTER COLUMN "saleableValue" SET DATA TYPE TEXT;
