export type CoinGeckoResponse = {
  id: string;
  symbol: string;
  name: string;
  image: string;
  current_price: number;
  market_cap: number;
  market_cap_rank: number;
  fully_diluted_valuation: number;
  total_volume: number;
  high_24h: number;
  low_24h: number;
  price_change_24h: number;
  price_change_percentage_24h: number;
  market_cap_change_24h: number;
  market_cap_change_percentage_24h: number;
  circulating_supply: number;
  total_supply: number;
  max_supply: number;
  ath: number;
  ath_change_percentage: number;
  ath_date: string;
  atl: 72.61;
  atl_change_percentage: number;
  atl_date: string;
  roi: undefined;
  last_updated: string;
};

export type ParsedCrypto = {
  name: string;
  type: "CRYPTOCURRENCY";
  ticker: string;
  currency: string;
  price: string;
  priceChange24h: string;
  priceChange24hPercent: string;
  image: string;
  marketCap: string;
  marketCapRank: string;
};
