spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/finance
    username: user
    password: iBaLbAHI4184N7J6
  security:
    user:
      name: admin
      password: admin-password
  flyway:
    locations: classpath:db/migration,classpath:db/testdata
    baseline-on-migrate: true
    validate-on-migrate: true
