#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "This is a trunk based development branch"
echo "Therefore tests, linting and build must pass before pushing"
echo
echo "======== Testing 🧪  ========"
yarn test
echo "======== Testing ✅  ========"
echo
echo "======== Linting 🔬  ========"
yarn lint
echo "======== Linting ✅  ========"
echo
echo "======== Building 🏗️ ========"
yarn build
echo "======== Building ✅ ========"
echo
echo "Test ✅ Lint ✅ Build ✅ pushed 🚀"
