name: reviewdog
on: [pull_request]
jobs:
  reviewdog:
    name: reviewdog
    runs-on: ubuntu-latest
    steps:
      - name: Setup reviewdog
        uses: reviewdog/action-setup@v1.0.3
      - name: Run tsc with reviewdog
        uses: EPMatt/reviewdog-action-tsc@v1.3.0
      - name: Run misspell with reviewdog
        uses: reviewdog/action-misspell@v1.12.3
      - name: Run eslint with reviewdog
        uses: reviewdog/action-eslint@v1.18.0
