name: Reviewdog

on: [pull_request]

jobs:
  eslint:
    name: eslint
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run eslint -- -f json -o eslint-report.json

      - name: Run Reviewdog
        uses: reviewdog/action-eslint@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          eslint_flags: '-f json -o eslint-report.json'
          level: warning
          filter_mode: file
